- README.md
- src/test/java/com/vaadin/ui/progressbar/ProgressBarIT.java
- src/test/java/com/vaadin/ui/progressbar/ProgressBarView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/6)
> Switch to jetty:run for running demo and IT test

- README.md
- pom.xml
- src/test/java/com/vaadin/ui/progressbar/ProgressBarIT.java
- src/test/java/com/vaadin/ui/progressbar/ProgressBarView.java
this is related to ticket vaadin/flow#2795
+Update router titles;
+Override getTestPath();
+Update parent and dependency version to SNAPSHOT;
+Update README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/9)
> Prepare to build Demo jar of the component

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/10)
> Add button dependency for test

- src/test/java/com/vaadin/ui/progressbar/demo/ProgressBarView.java
- src/test/java/com/vaadin/ui/progressbar/tests/ProgressBarIT.java
- src/test/java/com/vaadin/ui/progressbar/tests/ProgressBarTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/13)
> Refactor the repo structure

- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
- src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
- src/test/java/com/vaadin/flow/component/progressbar/demo/ProgressBarView.java
- src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarIT.java
- src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarTest.java
The part of the package rename #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/14)
> Rename package com.vaadin.ui to com.vaadin.flow.component

- pom.xml
- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
- src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
- src/test/java/com/vaadin/flow/component/progressbar/demo/ProgressBarView.java
The part of the package rename #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/15)
> Update imports due the package rename in the server module

- src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/17)
> Correct import in IT tests

- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
- src/test/java/com/vaadin/flow/component/progressbar/demo/ProgressBarView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/19)
> Update generated component and add lumo style to demos

- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
- src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
- src/test/java/com/vaadin/flow/component/progressbar/demo/ProgressBarView.java
- src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarTest.java
Update test class;
update generated files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/20)
> Update Java API

- pom.xml
- src/test/java/com/vaadin/flow/component/progressbar/demo/ProgressBarView.java
renaming repository ids;
enable logging;
remove HtmlImport from component demo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/21)
> Using new webjars

- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
fix after vaadin/flow#3678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/24)
> Update generated code

- pom.xml
- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/25)
> Update web component version to 1.0.0-beta2

- pom.xml
- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/26)
> Update vaadin-progress-bar to 1.0.0

- src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
- src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/29)
> State min and max values explicitly when throwing exceptions

- pom.xml
- src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarSerializableTest.java
Related to vaadin/platform#173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/32)
> Add serialization test

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/37)
> Update README about branch scheme

- pom.xml
- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
- src/main/java/com/vaadin/flow/component/progressbar/ProgressBarVariant.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/39)
> Update wejbars with Material Theme

- src/test/java/com/vaadin/flow/component/progressbar/demo/ProgressBarView.java
- src/test/java/com/vaadin/flow/component/progressbar/tests/ProgressBarIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/42)
> Add theme variant Demo and tests

- src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
- src/main/java/com/vaadin/flow/component/progressbar/ProgressBarVariant.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/45)
> Update java wrapper to stable version

- README.md
- vaadin-progress-bar-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/49)
> Update readme and add logger dependency

- pom.xml
- vaadin-progress-bar-flow-demo/pom.xml
- vaadin-progress-bar-flow-integration-tests/pom.xml
- vaadin-progress-bar-flow-testbench/pom.xml
- vaadin-progress-bar-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/52)
> Update to next minor and Use flow 1.5-SNAPSHOT

- vaadin-progress-bar-flow-integration-tests/pom.xml
- vaadin-progress-bar-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/55)
> Make TB artifactId consistent with other components

- pom.xml
- vaadin-progress-bar-flow-integration-tests/pom-bower-mode.xml
- vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/GeneratedVaadinProgressBar.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/56)
> Add bower tests.

- vaadin-progress-bar-flow-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/57)
> Add maven plugin to integration test pom.

- vaadin-progress-bar-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/58)
> Update webjar dependencies for release

- pom.xml
- vaadin-progress-bar-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/59)
> Remove vaadin-components-testbench

- pom.xml
Fixes SNAPSHOT failure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/60)
> Move bower mode test above NPM mode test due issue with influencing NPM mode by previously executed module

- pom.xml
- vaadin-progress-bar-flow-integration-tests/pom-bower-mode.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/61)
> Fix integration test build.

- vaadin-progress-bar-flow/pom.xml
- vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/62)
> Bump versions, update WC dependency to 1.1.1

- vaadin-progress-bar-flow/pom.xml
- vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/63)
> Bump web component dependency to 1.1.2

- vaadin-progress-bar-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/64)
> Only use flow-maven-plugin when packaging is war

- vaadin-progress-bar-flow-demo/src/main/java/com/vaadin/flow/component/progressbar/demo/ProgressBarView.java
This issue is for users to be able to use code correctly by copy-pasting
Depends on https://github.com/vaadin/flow/pull/8199/files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/68)
> Adding missing method to Vaadin Progress Bar demos

- pom.xml
- vaadin-progress-bar-flow-demo/pom.xml
- vaadin-progress-bar-flow-integration-tests/pom-bower-mode.xml
- vaadin-progress-bar-flow-integration-tests/pom.xml
- vaadin-progress-bar-flow-testbench/pom.xml
- vaadin-progress-bar-flow/pom.xml
- vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/71)
> Bump versions for V14.3

- pom.xml
- vaadin-progress-bar-flow-demo/pom.xml
- vaadin-progress-bar-flow-integration-tests/pom.xml
- vaadin-progress-bar-flow-testbench/pom.xml
- vaadin-progress-bar-flow/pom.xml
- vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/72)
> Update Flow and web component version

- pom.xml
- vaadin-progress-bar-flow-demo/pom.xml
- vaadin-progress-bar-flow-integration-tests/pom.xml
- vaadin-progress-bar-flow-testbench/pom.xml
- vaadin-progress-bar-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/73)
> Prepare next major

- vaadin-progress-bar-flow/src/main/java/com/vaadin/flow/component/progressbar/ProgressBar.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-progress-bar-flow/74)
> Bump Web Component version to 1.3.0-beta1
